---
title: "p8105_hw5_sl5010"
author: "Fiona Li"
date: "11/18/2021"
output: github_document
---

```{r}
library(tidyverse)
```

## Problem 1

```{r}
homicides_df = read_csv("Data/homicide-data.csv")
```

```{r}
# Describe the raw data
homicides_df = 
  homicides_df %>%
 mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved",
    )
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```

```{r}
aggregate_df = 
  homicides_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
aggregate_df
```

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved), 
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>% 
  broom::tidy()
```

```{r}
results_df = 
  aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```

```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 2

```{r,message = FALSE}
path_df = 
  tibble(
    path = list.files("Data/lda_data/"),
  ) %>% 
  mutate(
    path = str_c("Data/lda_data/", path),
    data = map(.x=path, read_csv)) %>%
unnest()
head(path_df)
```
```{r}
### Tidy the data
path_df = 
path_df %>%
janitor::clean_names() %>%
separate(path, into = c("Data", "lda_data", "path"), sep ="/") %>%
separate(path, into = c("control_arm", "subject_ID"), sep ="_") %>%
  mutate(subject_ID = str_replace(subject_ID, ".csv", "")) %>%
  select(-Data, -lda_data) %>%
    pivot_longer(
    week_1:week_8,
    names_to = "week", 
    values_to = "value")
path_df
```

```{r}
## Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups.
path_df %>%
    ggplot(aes(x = week, y = value, color = subject_ID, group = subject_ID)) +
  labs(title = " observations on each subject over time") + geom_line() +
  facet_grid(. ~ control_arm)

```

**comment on differences between groups.** For the control group, the trend is not positive, and for experiment group, we see a positive trend, that is, the value increases while time increases. 

## Problem 3

```{r}
## loading the data set
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
iris_with_missing
```

```{r}
## Write a function that takes a vector as an argument; replaces missing values using the rules defined above; and returns the resulting vector. 

missing_value = function(x) {
   if (is.numeric(x)) {
     replace_na(x, round(mean(x,na.rm = TRUE), digits = 1))
   }
  else if(is.character(x)){
    replace_na(x,"virginica")
  }
} 

map_dfr(iris_with_missing, missing_value)
```

